apiVersion: v1
kind: Service
metadata:
  name:  redis
spec:
  selector:
    app: redis
  type:  NodePort
  ports:
  - protocol: TCP
    name:  redis
    port:  6379
    targetPort:  redis
    nodePort:  30555