# This file contains the Kubernetes configuration for deploying a Redis instance.
# Based on https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/pods/config/redis-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis:5.0.4
    command:
      - redis-server
      - "/redis-master/redis.conf"
    resources:
      limits:
        cpu: '0.1'
    env:
    - name: MASTER
      value: "true"
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 6379
    volumeMounts:
      - mountPath: /redis-master-data
        name: data
      - mountPath: /redis-master
        name: config
  volumes:
  - name: data
    emptyDir: {}
  - name: config
    configMap:
      name: example-redis-config
      items:
      - key: redis-config
        path: redis.conf
